# 第5章 误差反向传播法

高效计算权重参数的梯度的方法——误差反向传播法。

要正确理解误差反向传播法，我个人认为有两种方法：
一种是基于数学式；
另一种是基于**计算图**（computational graph）。

## 5.1 计算图

计算图将计算过程用图形表示出来。

### 5.1.1 用计算图求解

**问题1**：太郎在超市买了2个100日元一个的苹果，消费税是10%，请计算支付金额。

![图5-1.基于计算图求解的问题1的答案](../images/图5-1.基于计算图求解的问题1的答案.PNG)
图5-1.基于计算图求解的问题1的答案

![图5-2.基于计算图求解的问题1的答案：“苹果的个数”和“消费税”作为变量标在○外面](../images/图5-2.基于计算图求解的问题1的答案：“苹果的个数”和“消费税”作为变量标在○外面.PNG)
图5-2.基于计算图求解的问题1的答案：“苹果的个数”和“消费税”作为变量标在○外面

**问题2**：太郎在超市买了2个苹果、3个橘子。其中，苹果每个100日元，
橘子每个150日元。消费税是10%，请计算支付金额。

![图5-3.基于计算图求解的问题2的答案](../images/图5-3.基于计算图求解的问题2的答案.PNG)
图5-3.基于计算图求解的问题2的答案

用计算图解题：
1. 构建计算图。
2. 在计算图上，从左向右进行计算

这里的第2歩“从左向右进行计算”是一种正方向上的传播，简称为**正向传播**（forward propagation）。
正向传播是从计算图出发点到结束点的传播。
也可以考虑反向（从图上看的话，就是从右向左）的传播。实际上，这种传播称为**反向传播**（backward propagation）。

### 5.1.2 局部计算

![图5-4.买了2个苹果和其他很多东西的例子](../images/图5-4.买了2个苹果和其他很多东西的例子.PNG)
图5-4.买了2个苹果和其他很多东西的例子

### 5.1.3 为何用计算图解题

计算图到底有什么优点呢？
1. 局部计算，无论全局是多么复杂的计算，都可以通过局部计算使各个节点致力于简单的计算，从而简化问题。
2. 保存中间结果，利用计算图可以将中间的计算结果全部保存起来。
3. 使用计算图最大的原因是，可以通过反向传播高效计算导数。

![图5-5.基于反向传播的导数的传递](../images/图5-5.基于反向传播的导数的传递.PNG)
图5-5.基于反向传播的导数的传递

## 5.2 链式法则

反向传播将局部导数向正方向的反方向（从右到左）传递，一开始可能会让人感到困惑。
传递这个局部导数的原理，是基于**链式法则**（chain rule）的。

### 5.2.1 计算图的反向传播

![图5-6.计算图的反向传播：沿着与正方向相反的方向，乘上局部导数](../images/图5-6.计算图的反向传播：沿着与正方向相反的方向，乘上局部导数.PNG)
图5-6.计算图的反向传播：沿着与正方向相反的方向，乘上局部导数

反向传播的计算顺序是，将信号 $E$ 乘以节点的局部导数（$\frac{\partial y}{\partial x}$），然后将结果传递给下一个节点。

通过这样的计算，可以高效地求出导数的值，这是反向传播的要点。

### 5.2.2 什么是链式法则

**复合函数**：由多个函数构成的函数。

$$
    z = t^2 \\
    t = x + y \tag{5.1}
$$

链式法则是关于复合函数的导数的性质：
    如果某个函数由复合函数表示，则复合函数的导数可以构成复合函数的各个函数的导数的乘积表示。

$$
    \frac{\partial z}{\partial x} = \frac{\partial z}{\partial t} \frac{\partial t}{\partial x} \tag{5.2}
$$

先求式（5.1）中的局部导数（偏导数）。
$$
    \frac{\partial z}{\partial t} = 2t  \\
    \frac{\partial t}{\partial x} = 1   \tag{5.3}
$$

$$
    \frac{\partial z}{\partial x} = \frac{\partial z}{\partial t} \frac{\partial t}{\partial x} = 2t \cdot 1 = 2(x + y) \tag{5.4}
$$

### 5.2.3　链式法则和计算图

![图5-7.式（5.4）的计算图：沿着与正方向相反的方向，乘上局部导数后传递](../images/图5-7.PNG)
图5-7.式（5.4）的计算图：沿着与正方向相反的方向，乘上局部导数后传递


![](../images/图5-8.PNG)

反向传播是基于链式法则的。

## 5.3 反向传播

### 5.3.1 加法节点的反向传播

$ z=x+y $ 的导数可由下式解析性地计算出来：
$$ \frac{\partial z}{\partial x} = 1    \\
    \frac{\partial z}{\partial y} = 1
    \tag{5.5} $$

![图5-9](../images/图5-9.PNG)
图5-9

![图5-10](../images/图5-10.PNG)
图5-10

![图5-11.加法节点的反向传播的具体例子](../images/图5-11.加法节点的反向传播的具体例子.PNG)
图5-11.加法节点的反向传播的具体例子

### 5.3.2 乘法节点的反向传播

$ z = xy $ 式子的导数用式（5.6）表示：

$$
    \frac{\partial z}{\partial x} = y    \\
    \frac{\partial z}{\partial y} = x
    \tag{5.6}
$$

![](../images/图5-12.PNG)
图5-12.乘法的反向传播：左图是正向传播，右图是反向传播

![图5-13.乘法节点的反向传播的具体例子](../images/图5-13.乘法节点的反向传播的具体例子.PNG)
图5-13.乘法节点的反向传播的具体例子

### 5.3.3　苹果的例子

![图5-14.购买苹果的反向传播的例子](../images/图5-14.购买苹果的反向传播的例子.PNG)
图5-14.购买苹果的反向传播的例子

![](../images/图5-15.购买苹果和橘子的反向传播的例子：在方块中填入数字，完成反向传播.PNG)
图5-15.购买苹果和橘子的反向传播的例子：在方块中填入数字，完成反向传播

## 5.4 简单层的实现

### 5.4.1 乘法层的实现

[ch05/layer_naive.py](/ch05/layer_naive.py)

In [2]:
import numpy as np


class MulLayer:
    """
    乘法层实现
    """

    def __init__(self):
        self.x = None
        self.y = None

    def forward(self, x, y):
        self.x = x
        self.y = y
        out = x * y

        return out

    def backward(self, dout):
        dx = dout * self.y  # 翻转x和y
        dy = dout * self.x

        return dx, dy

backward()将从上游传来的导数（dout）乘以正向传播的翻转值，然后传给下游。

![图5-16.购买2个苹果](../images/图5-16.购买2个苹果.PNG)
图5-16.购买2个苹果

[ch05/buy_apple.py](/ch05/buy_apple.py)

backward()的参数中需要输入“关于正向传播时的输出变量的导数”。

### 5.4.2 加法层的实现

In [3]:
class AddLayer:
    """
    加法层实现
    """

    def __init__(self):
        pass

    def forward(self, x, y):
        out = x + y

        return out

    def backward(self, dout):
        dx = dout * 1
        dy = dout * 1

        return dx, dy

![图5-17.购买2个苹果和3个橘子](../images/图5-17.PNG)
图5-17.购买2个苹果和3个橘子

[ch05/buy_apple_orange.py](/ch05/buy_apple_orange.py)

用Python实现图5-17的计算图的过程如下所示：

In [4]:
apple = 100
apple_num = 2
orange = 150
orange_num = 3
tax = 1.1

# layer
mul_apple_layer = MulLayer()
mul_orange_layer = MulLayer()
add_apple_orange_layer = AddLayer()
mul_tax_layer = MulLayer()

# forward
apple_price = mul_apple_layer.forward(apple, apple_num)  # 1
orange_price = mul_orange_layer.forward(orange, orange_num)  # 2
all_price = add_apple_orange_layer.forward(apple_price, orange_price)  # 3
price = mul_tax_layer.forward(all_price, tax)  # 4

# backward
dprice = 1
dall_price, dtax = mul_tax_layer.backward(dprice)  # 4
dapple_price, dorange_price = add_apple_orange_layer.backward(dall_price)  # 3
dorange, dorange_num = mul_orange_layer.backward(dorange_price)  # 2
dapple, dapple_num = mul_apple_layer.backward(dapple_price)  # 1

print(price)  # 715
print(dapple_num, dapple, dorange, dorange_num, dtax)  # 110 2.2 3.3 165 650

715.0000000000001
110.00000000000001 2.2 3.3000000000000003 165.0 650


## 5.5 激活函数的实现

激活函数的ReLU层和Sigmoid层

### 5.5.1 ReLU层

激活函数ReLU（Rectified Linear Unit）由下式（5.7）表示。

$$
y =
\left\{\begin{matrix}
    x \ (x>0) \\
    0 \ (x \leqslant 0)
\end{matrix}\right.
\tag{5.7}
$$

通过式（5.7），可以求出y关于x的导数，如式（5.8）所示。

$$
\frac{\partial y}{\partial x} =
\left\{\begin{m}
    1 \ (x>0)   \\
    0 \ (x \leqslant 0)
\end{m}\right.
\tag{5.8}
$$



![图5-18.ReLU层的计算图](../images/图5-18.ReLU层的计算图.PNG)
图5-18.ReLU层的计算图

In [5]:
class Relu:
    def __init__(self):
        self.mask = None

    def forward(self, x):
        self.mask = (x <= 0)
        out = x.copy()
        out[self.mask] = 0  # 将 <=0 的元素设置为0

        return out

    def backward(self, dout):
        dout[self.mask] = 0
        dx = dout

        return dx

In [6]:
x = np.array([[1.0, -0.5], [-2.0, 3.0]])
x

array([[ 1. , -0.5],
       [-2. ,  3. ]])

In [7]:
mask = (x <= 0)
mask

array([[False,  True],
       [ True, False]])

### 5.5.2 Sigmoid层

sigmoid函数由式（5.9）表示。

$$  y = \frac{1}{1 + \exp(-x)} \tag{5.9} $$

![](../images/图5-19.sigmoid层的计算图（仅正向传播）.PNG)
图5-19.sigmoid层的计算图（仅正向传播）

* 步骤1

“/”节点表示 $y = \frac{1}{x}$，它的导数：

$$
    \frac{\partial y}{\partial x} = - \frac{1}{x^2} \\
               = -y^2   \tag{5.10}
$$

![步骤1](../images/步骤1.PNG)

* 步骤2

”+“节点将上游的值原封不动地传给下游。

![步骤2](../images/步骤2.PNG)

* 步骤3

”exp“节点表示 $y=\exp(x)$ ，它的导数：

$$
     \frac{\partial y}{\partial x} = \exp (x)   \tag{5.11}
$$

计算图中，上游的值乘以正向传播时的输出（这个例子中是exp(−x)）后，再传给下游。

![步骤3](../images/步骤3.PNG)

* 步骤4

”x“节点将正向传播时的值翻转后做乘法运算。

![图5-20.Sigmoid层的计算图](../images/图5-20.Sigmoid层的计算图.PNG)
图5-20.Sigmoid层的计算图

![图5-21.Sigmoid层的计算图（简洁版）](../images/图5-21.Sigmoid层的计算图（简洁版）.PNG)
图5-21.Sigmoid层的计算图（简洁版）

$$
    \frac{\partial L}{\partial y} y^2 \exp(-x) = \frac{\partial L}{\partial y} \frac{1}{{1 + \exp(-x)}^2} \exp(-x)      \\
    = \frac{\partial L}{\partial y} \frac{1}{1 + \exp(-x)} \frac{\exp(-x)}{1 + \exp(-x)}     \\
    = \frac{\partial L}{\partial y} y (1 - y)      \\ \tag{5.12}
$$

![图5-22.Sigmoid层的计算图：可以根据正向传播的输出y计算反向传播](../images/图5-22.Sigmoid层的计算图：可以根据正向传播的输出y计算反向传播.PNG)
图5-22 Sigmoid层的计算图：可以根据正向传播的输出y计算反向传播

In [8]:
class Sigmoid:
    def __init__(self):
        self.out = None

    def forward(self, x):
        out = 1 / (1 + np.exp(-x))
        self.out = out

    def backward(self, dout):
        dx = dout * (1.0 - self.out) * self.out

        return dx

## 5.6 Affine/Softmax层的实现

### 5.6.1 Affine层

Affine 仿射

In [9]:
X = np.random.rand(2)  # 输入
W = np.random.rand(2, 3)  # 权重
B = np.random.rand(3)  # 偏置

X.shape, W.shape, B.shape  # ((2,), (2, 3), (3,))

((2,), (2, 3), (3,))

In [10]:
Y = np.dot(X, W) + B
Y

array([0.49269064, 0.64905752, 1.11747324])

神经网络的正向传播中进行的矩阵的乘积运算在几何学领域被称为“仿射变换”。
进行仿射变换的处理实现为“Affine层”。

几何中，仿射变换包括一次线性变换和一次平移，分别对应神经网络的加权和运算与加偏置运算。

![](../images/图5-24.Affine层的计算图.PNG)

$$
    \frac{\partial L}{\partial \textbf{X}} = \frac{\partial L}{\partial \textbf{Y}} \cdot \textbf{W}^T
    \\
    \frac{\partial L}{\partial \textbf{W}} = \textbf{X}^T \cdot  \frac{\partial L}{\partial \textbf{Y}}
    \\
    \tag{5.13}
$$

![](../images/图5-25.Affine层的反向传播.PNG)
图5-25 Affine层的反向传播

![](../images/图5-26.PNG)




### 5.6.2 批版本的Affine层


![图5-27.批版本的Affine层的计算图](../images/图5-27.批版本的Affine层的计算图.PNG)
图5-27.批版本的Affine层的计算图


In [11]:
X_dot_W = np.array([[0, 0, 0], [10, 10, 10]])
B = np.array([1, 2, 3])
X_dot_W

array([[ 0,  0,  0],
       [10, 10, 10]])

In [12]:
X_dot_W + B

array([[ 1,  2,  3],
       [11, 12, 13]])

In [13]:
dY = np.array([[1, 2, 3], [4, 5, 6]])
dY

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
dB = np.sum(dY, axis=0)
dB

array([5, 7, 9])

In [15]:
class Affine:
    def __init__(self, W, b):
        self.W = W
        self.b = b
        self.x = None
        self.dW = None
        self.db = None

    def forward(self, x):
        self.x = x
        out = np.dot(x, self.W) + self.b

        return out

    def backward(self, dout):
        dx = np.dot(dout, self.W.T)
        self.dW = np.dot(self.x.T, dout)
        self.db = np.sum(dout, axis=0)

        return dx


### 5.6.3 Softmax-with-Loss层

![](../images/图5-28.PNG)

![图5-29.Softmax-with-Loss层的计算图](../images/图5-29.Softmax-with-Loss层的计算图.PNG)
图5-29.Softmax-with-Loss层的计算图

![图5-30.“简易版”的Softmax-with-Loss层的计算图](../images/图5-30.“简易版”的Softmax-with-Loss层的计算图.PNG)
图5-30.“简易版”的Softmax-with-Loss层的计算图

In [16]:
from common.functions import softmax, cross_entropy_error


class SoftmaxWithLoss:
    def __init__(self):
        self.loss = None  # 损失
        self.y = None  # softmax的输出
        self.t = None  # 监督数据（one-hot vector）

    def forward(self, x, t):
        self.t = t
        self.y = softmax(x)
        self.loss = cross_entropy_error(self.y, self.t)

        return self.loss

    def backward(self, dout=1):
        batch_size = self.t.shape[0]
        dx = (self.y - self.t) / batch_size

        return dx

## 5.7 误差反向传播法的实现

ch05/two_layer_net.py


### 5.7.1 神经网络学习的全貌图

* 前提
神经网络中有合适的权重和偏置，调整权重和偏置以便拟合训练数据的
过程称为学习。神经网络的学习分为下面4个步骤。

* 步骤1（mini-batch）
从训练数据中随机选择一部分数据。

* 步骤2（计算梯度）
计算损失函数关于各个权重参数的梯度。

* 步骤3（更新参数）
将权重参数沿梯度方向进行微小的更新。

* 步骤4（重复）
重复步骤1、步骤2、步骤3。

### 5.7.2　对应误差反向传播法的神经网络的实现

2层神经网络实现为TwoLayerNet：
[/ch05/two_layer_net.py](/ch05/two_layer_net.py)

### 5.7.3 误差反向传播法的梯度确认

两种求梯度的方法：
1. 基于数值微分
2. 解析性地求解数学式：误差反向传播法

在确认误差反向传播法的实现是否正确时，是需要用到数值微分的。

确认数值微分求出的梯度结果和误差反向传播法求出的结果是否一致（严格地讲，是非常相近）的操作称为**梯度确认**（gradient check）。

[梯度确认的代码实现](/ch05/gradient_check.py)

### 5.7.4 使用误差反向传播法学习

[/ch05/train_neuralnet.py](/ch05/train_neuralnet.py)

## 5.8 小结

* 通过使用计算图，可以直观地把握计算过程
* 计算图的节点是由局部计算构成的。局部计算构成全局计算。
* 计算图的正向传播进行一般的计算。通过计算图的反向传播，可以计算各个节点的导数。
* 通过将神经网络的组成元素实现为层，可以高效地计算梯度（反向传播法）。
* 通过比较数值微分和误差反向传播法的结果，可以确认误差反向传播法的实现是否正确（梯度确认）。